### PR TITLE
Disclaimer data privacy policy

### PR DESCRIPTION
**Pull request by NicolasAntoine**
added a disclaimer about the data privacy policy

### CODE REVIEW

**Comment by Vikranth3140** [comment]
Hey @NicolasAntoine,

Thanks for the PR to close #8.
The PR lgtm, please send a screenshot of the application displaying the user data privacy notice.

**Comment by NicolasAntoine** [comment]
There it is. Don’t hesitate to tell me if it must be modified 😊

De : Vikranth Udandarao ***@***.***>
Envoyé : lundi 4 novembre 2024 18:44
À : Vikranth3140/Mental-Health-Support-Chatbot ***@***.***>
Cc : Nicolas Antoine ***@***.***>; Mention ***@***.***>
Objet : Re: [Vikranth3140/Mental-Health-Support-Chatbot] Disclaimer data privacy policy (PR #16)

Vous n’obtenez pas souvent d’e-mail à partir de ***@***.******@***.***>. Pourquoi c’est important<https://aka.ms/LearnAboutSenderIdentification>

Hey @NicolasAntoine<https://github.com/NicolasAntoine>,

Thanks for the PR to close #8<https://github.com/Vikranth3140/Mental-Health-Support-Chatbot/issues/8>.
The PR lgtm, please send a screenshot of the application displaying the user data privacy notice.

**Comment by Vikranth3140** [comment]
Hey @NicolasAntoine,

I can't find the screenshot, please send it again.

**Comment by NicolasAntoine** [comment]
> Hey @NicolasAntoine,
> 
> I can't find the screenshot, please send it again.

Capture d’écran 2024-11-04 204102

**Review by Vikranth3140 — APPROVED** [review]
lgtm

**Comment by Vikranth3140** [comment]
Hey @NicolasAntoine,

Thanks for your PR to close #8.
Congratulations on your first merged PR.

Do checkout other repositories to contribute [here](https://github.com/Vikranth3140?tab=repositories)

**Pull request merged**
